FROM python:3.11-slim-buster
WORKDIR .
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5000
ENV FLASK_APP=FindStock.py
CMD ["python", "-m", "flask", "--app", "FindStock", "run"]
